---
name: magic
on: 
  workflow_dispatch: 
    inputs: 
      version: 
        description: 'Version to release (ex. v0.1)' 
        required: true 
 
jobs: 
  deploy: 
    name: Deploy rubysocial to production cluster 
    runs-on: ubuntu-18.04
    steps: 
      - name: Check Out Repo 
        uses: actions/checkout@v2 

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          project_id: ${{ secrets.GCS_PROJECT }}
          export_default_credentials: true

      - name: Install kube config 
        env: 
          INPUT_KUBECONFIG: ${{ secrets.KUBE_CONFIG_DATA }} 
        run: | 
          mkdir ~/.kube/ || true 
          echo "${INPUT_KUBECONFIG}" > ~/.kube/config 
          chmod 700 ~/.kube/config   

      - name: Deploy to Kubernetes 
        run: 
          helm upgrade rubysocial ./deployment/rubysocial/ --install --wait --atomic  --set=version=${{ github.event.inputs.version }} --kubeconfig ~/.kube/config 