---
name: magic
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  backend-frontend:
    name: Create backend and frontend releases
    runs-on: ubuntu-20.04
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_LOGIN }}/rubysocial:${{ steps.get_version.outputs.VERSION }}
          build-args: |
            RAILS_KEY=${{ secrets.RAILS_KEY }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Extract static files
        id: extract
        uses: shrink/actions-docker-extract@v1
        with:
          image: ${{ secrets.DOCKER_HUB_LOGIN }}/rubysocial:${{ steps.get_version.outputs.VERSION }}
          path: /usr/src/app/public/.

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          project_id: ${{ secrets.GCS_PROJECT }}
          export_default_credentials: true

      - name: Copy files to GCS
        run: |
          gsutil rsync -r ${{ steps.extract.outputs.destination }}/packs gs://${{ secrets.GCS_BUCKET }}/${{ steps.get_version.outputs.VERSION }}/packs
 
  deploy: 
    name: Deploy rubysocial to stage cluster 
    runs-on: ubuntu-20.04
    needs: [backend-frontend]
    steps: 
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          project_id: ${{ secrets.GCS_PROJECT }}
          export_default_credentials: true

      - name: Install kube config 
        env: 
          INPUT_KUBECONFIG: ${{ secrets.KUBE_CONFIG_DATA }} 
        run: | 
          mkdir ~/.kube/ || true 
          echo "${INPUT_KUBECONFIG}" > ~/.kube/config 
          chmod 700 ~/.kube/config   

      - name: Deploy to Kubernetes 
        run: 
          helm upgrade rubysocial ./deployment/rubysocial/ --install --wait --atomic  --set=version=${{ steps.get_version.outputs.VERSION }} --kubeconfig ~/.kube/config 