name: release
on:
  push:
    tags:
      - 'p*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  backend-frontend:
    name: Create backend and frontend releases
    runs-on: ubuntu-18.04
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_LOGIN }}/rubysocial:${{ steps.get_version.outputs.VERSION }}
          build-args: |
            RAILS_KEY=${{ secrets.RAILS_KEY }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Extract static files
        id: extract
        uses: shrink/actions-docker-extract@v1
        with:
          image: ${{ secrets.DOCKER_HUB_LOGIN }}/rubysocial:${{ steps.get_version.outputs.VERSION }}
          path: /usr/src/app/public/.

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          service_account_key: ${{ secrets.PROD_SA_KEY }}
          project_id: ${{ secrets.PROD_PROJECT }}
          export_default_credentials: true

      - name: Copy files to GCS
        run: |
          gsutil rsync -r ${{ steps.extract.outputs.destination }}/packs gs://${{ secrets.PROD_BUCKET }}/${{ steps.get_version.outputs.VERSION }}/packs